# Generated by Django 4.1.6 on 2023-02-22 02:46

from django.db import migrations, models
import task_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, validators=[task_management.models.Tarefa.validate_completion_date]),
        ),
    ]
